spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bella_foundation
spring.datasource.username=sa
spring.datasource.password=Hakeju9779

# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.datasource.test-while-idle=true
spring.datasource.test-on-borrow=true
spring.datasource.auto-commit=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


### kafka Configurations
kafka.bootStrapAddress= pkc-60py3.europe-west9.gcp.confluent.cloud:9092
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=ZKNN2MWOXKRFJ3ZC password=9Sux4qSg5cSbYoYM7zDmL3jpQpfyYYW55zb6mLptrO33pj+8NFka93GUG3wytd2B
sasl.mechanism=PLAIN
security,protocal=SASL_SSL

### Kafka Topics
topic.test=TestTopic
